name: Notify Discord on Push

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        uses: https://discord.com/api/webhooks/
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          content: "A new push has been made to the repository"
